jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLabx
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1 
          when: on_fail
    
  nuclei_dast:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull projectdiscovery/nuclei:v2.9.1
          docker run --user $(id -u):$(id -g) -w /nuclei -v $(pwd):/nuclei:rw --rm projectdiscovery/nuclei:v2.9.1 -u https://prod-khbdop1h.lab.practical-devsecops.training -j -o nuclei-output.json || true

      - store_artifacts:
          path: nuclei-output.json
          destination: nuclei-output
          

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - nuclei_dast:
          requires:
            - integration
      - prod:
          type: approval
          requires:
            - nuclei_dast
