jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  oast-snyk:
    docker: 
      - image: node:latest
    steps:
      - checkout
      - run:
          command: |
            - wget -O snyk https://github.com/snyk/snyk/releases/download/v1.566.0/snyk-linux
            - chmod +x snyk
            - mv snyk /usr/local/bin/
            - npm install
            - snyk test --json > snyk-results.json || true 
      - store_artifacts:
          path: snyk-results.json
          destination: snyk-file

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration