name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-20.04                    # similar to "image" in GitLab #
    steps:
      - uses: actions/checkout@v2            

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  nuclei_dast:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: |
          docker pull projectdiscovery/nuclei:v2.9.1
          docker run --user $(id -u):$(id -g) -w /nuclei -v $(pwd):/nuclei:rw --rm projectdiscovery/nuclei:v2.9.1 -u https://prod-kbesuu8i.lab.practical-devsecops.training -j -o nuclei-output.json 
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          name: nuclei-output
          path: nuclei-output.json 
        if: always()        # what is this for?

        
  prod:
    runs-on: ubuntu-20.04
    needs: nuclei_dast
    steps:
      - run: echo "This is a deploy step."
